# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='json_workflow',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='layout',
            field=jsonfield.fields.JSONField(),
        ),
    ]
